
  name: vpnconnectgui
  version: 'git'
  summary: Use openvpn with GUI
  description: |
    An application with Graphical User Interface that lets you connect to VPN server with openvpn written in Python3 with Gtk3 required package: openvpn notify-osd libnotify-bin

  grade: devel # must be 'stable' to release into candidate/stable channels
  confinement: devmode # use 'strict' once you have the right plugs and slots

  parts:
    vpnconnectgui:
      plugin: python
      python-version: python3
      source: .
      build-packages:
        - openvpn
        - libnotify-bin
        - notif-osd
  
